apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kkzj0hu63-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:fbe4057a93c31e73f40470fba6f5b8c7f3fa73e0@sha256:213bdf6de56e7d16d4f3109768919b82a5aaa108038c73af9cbc9ee68052bf7d
          name: container-image
