apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kkzj0hu63-go
  janus-idp.io/tekton: kkzj0hu63-go
  backstage.io/kubernetes-id: kkzj0hu63-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kkzj0hu63-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
